language: node_js
node_js:
  - "0.10"
before_install: 
  - npm install -g grunt-cli bower
  - gem install compass
install:
  - npm install
  - bower install
  - cd tests && bower install
before_script: grunt build
script: grunt test
